---
- name: Clean node and data directory
  hosts: all
  tasks:
    - name: Stop services
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - bor
        - heimdalld
      become: yes

    - name: remove installed binaries
      shell: apt remove bor bor-profile heimdalld heimdalld-profile -y
      become: true

