---
- name: Network node management
  hosts: all
  tasks:
    - name: update permission for home 
      shell: chmod 755 {{ ansible_env.HOME }}/
      become: true
    
    - name: Install Dependencies
      include_role:
        name: roles/install-dependencies

    - name: Install Heimdall
      include_role:
        name: roles/install-heimdall

    - name: Install Bor
      include_role:
        name: roles/install-bor

